name: Check out the repositories
description: Checks out the pulumi-awsx and optionally the pulumi/scripts repos

inputs:
  shallow:
    description: Set to "true" for a shallow clone without tags

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Checkout Scripts Repo
      uses: actions/checkout@v4
      with:
        path: ci-scripts
        repository: pulumi/scripts
    - if: shallow != 'true'
      name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags